const titleGenders = [
  { name: 'Ação', value: 'acao' },
  { name: 'Animação', value: 'animacao' },
  { name: 'Artes Marciais', value: 'artes-marciais' },
  { name: 'Aventura', value: 'aventura' },
  { name: 'Biográfico', value: 'biografico' },
  { name: 'Comédia', value: 'comedia' },
  { name: 'Comédia Romântica', value: 'comedia-romantica' },
  { name: 'Crime', value: 'crime' },
  { name: 'Cultura', value: 'cultura' },
  { name: 'Dança', value: 'danca' },
  { name: 'Documentário', value: 'documentario' },
  { name: 'Drama', value: 'drama' },
  { name: 'Esporte', value: 'esporte' },
  { name: 'Espionagem', value: 'espionagem' },
  { name: 'Família', value: 'familia' },
  { name: 'Fantasia', value: 'fantasia' },
  { name: 'Faroeste', value: 'faroeste' },
  { name: 'Ficção Científica', value: 'ficcao-cientifica' },
  { name: 'Guerra', value: 'guerra' },
  { name: 'História', value: 'historia' },
  { name: 'Mistério', value: 'misterio' },
  { name: 'Musical', value: 'musical' },
  { name: 'Noir', value: 'noir' },
  { name: 'NSFW', value: 'nsfw' },
  { name: 'Perturbador', value: 'perturbador' },
  { name: 'Policial', value: 'policial' },
  { name: 'Reality Show', value: 'reality-show' },
  { name: 'Romance', value: 'romance' },
  { name: 'Super-Heróis', value: 'super-herois' },
  { name: 'Suspense', value: 'suspense' },
  { name: 'Terror', value: 'terror' },
  { name: 'Thriller Psicológico', value: 'thriller-psicologico' },
  { name: 'Outro não listado', value: 'outro' }
]

export default titleGenders
